### ISSUE TITLE
Unable to install the CAP file on a JavaCard JC3.0.4

### ISSUE THREAD

**Issue by sdellava** [david-oswald/jc_curve25519#4]
I’m trying to install the CAP file on this Javacard to test the performance: https://www.javacardos.com/store/products/10002

The GP2 correctly download the cap file, but it is not able to install the applet. This is the error I get:

INSTALL [for install and make selectable] failed: 0x6985 (Conditions of use not satisfied)

Warning: no keys given, using default test key  404142434445464748494A4B4C4D4E4F
 ISD: A0000001510000 (OP_READY)
Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement

PKG: C1C2C3C4C5 (LOADED)
Applet:  C1C2C3C4C5C6C7C8

**Comment by david-oswald** [comment]
I'm not fully sure, but from the specs of this card it seems that it doesn't have ECC acceleration, so that might be the reason?

**Comment by sdellava** [comment]
Yes, it could be the reason. I was not aware that the ECC accelerator was required. 

Can you suggest an appropriate smartcard?

**Comment by sdellava** [comment]
Ok. Clear. I'll try with the J2D081. Tnx

**Comment by david-oswald** [comment]
So it was tested successfully on those three:

 * NXP J2D081 contact 
 * NXP J3H145 contact 
 * NXP JCOP4 J3R180 contact

Any card with ECC support >= 256 bit should do, though it also makes sense to read some of the comments in the code if you can't get it to work.

**Comment by sdellava** [comment]
Any suggested NFC enabled card?

**Comment by martinpaljak** [comment]
Any contactless counterpart of the same product family (to get the same chip) ? both jcop4 and jcop3 (j3h145) have contactless/dual variants.
