### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by sdellava** [david-oswald/jc_curve25519#6]
The compile return and error:

build.bat

C:\Dev\tmp\jc_curve25519>ant -f build.xml curve
Buildfile: C:\Dev\tmp\jc_curve25519\build.xml

jcpro:
    [mkdir] Created dir: C:\Users\....\AppData\Local\Temp\jcpro320706545
    [javac] Compiling 1 source file to C:\Users\....\AppData\Local\Temp\jcpro320706545
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] warning: [options] source value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] 4 warnings

curve:
 [javacard] JavaCard 3.x SDK detected in ../../Curve25519/oracle_javacard_sdks/jc304_kit/
      [cap] Setting package name to curve25519
      [cap] Building CAP with 1 applet(s) from package curve25519
      [cap] curve25519.Curve25519Test C1C2C3C4C5C6C7C8
  [compile] Compiling 1 source file to C:\Users\Stefano\AppData\Local\Temp\antjc8599029505051022714
  [compile] error: Source option 5 is no longer supported. Use 7 or later.
  [compile] error: Target option 5 is no longer supported. Use 7 or later.

BUILD FAILED
C:\Users\....\Documents\Dev\tmp\jc_curve25519\build.xml:25: Compile failed; see the compiler error output for details.

Total time: 1 second

But I can't find where to fix those options.

**Comment by martinpaljak** [comment]
Use JDK-8 or target a different SDK: https://github.com/martinpaljak/ant-javacard/wiki/Version-compatibility

**Comment by sdellava** [comment]
Solved using jdk1.8.0_291. Tnx
